<?php
/**
 * Created by PhpStorm.
 * User: vash
 * Date: 24/02/20
 * Time: 4:39 PM
 */

namespace Vsynch\StripeIntegration\Controllers;

use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Laravel\Cashier\Http\Controllers\WebhookController;
use Stripe\Event;

class StripeController extends WebhookController
{

    public function handleCustomerSubscriptionDeleted(array $payload)
    {
        return parent::handleCustomerSubscriptionDeleted($payload); // TODO: Change the autogenerated stub
    }

    public function handleCustomerSubscriptionCreated( $payload)
    {
        try {
            $event = Event::constructFrom(
                json_decode($payload, true)
            );
        } catch(\UnexpectedValueException $e) {
            // Invalid payload
            http_response_code(400);
            exit();
        }
        Log::info(json_encode($event));
        return $this->successMethod();
    }

    public function handleCustomerSubscriptionUpdated( $payload)
    {
        try {
            $event = Event::constructFrom(
                json_decode($payload, true)
            );
        } catch(\UnexpectedValueException $e) {
            // Invalid payload
            http_response_code(400);
            exit();
        }
        Log::info(json_encode($event));
        return $this->successMethod();
    }

    public function handleInvoicePaymentSucceeded( $payload)
    {
        try {
            $event = Event::constructFrom(
                json_decode($payload, true)
            );
        } catch(\UnexpectedValueException $e) {
            // Invalid payload
            http_response_code(400);
            exit();
        }
        Log::info(json_encode($event));
        return $this->successMethod();
    }
}